version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8000:80"
  server:
    build: 
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "4000:4000"